development:
  adapter: postgresql
  host: localhost
  database: asterisk
  username: asterisk
  password: qwe129jk

test:
  adapter: postgresql
  host: localhost
  database: asterisk_test
  username: asterisk
  password: qwe129jk

production:
  adapter: postgresql
  host: localhost
  database: asterisk_prod
  username: asterisk
  password: qwe129jk
